function ReportPDF({ data, userId, aiAdvice, negotiationLetter }) {
  return (
    <div
      id="pdf-report"
      style={{
        background: "#ffffff",
        color: "#000",
        padding: "35px",
        width: "700px",
        margin: "0 auto",
        fontFamily: "Arial, sans-serif",
        boxSizing: "border-box",
      }}
    >
      {/* Header */}
      <div style={{ textAlign: "center", marginBottom: "25px" }}>
        <h1
          style={{
            color: "#1976d2",
            margin: 0,
            fontSize: "36px",
          }}
        >
          FinRelief AI
        </h1>

        <h2
          style={{
            fontSize: "26px",
            marginTop: "12px",
            marginBottom: "12px",
          }}
        >
          AI Powered Debt Relief &
          <br />
          Financial Recovery Platform
        </h2>

        <p
          style={{
            color: "#666",
            margin: 0,
          }}
        >
          Financial Analysis Report
        </p>
      </div>

      <hr />

      {/* Borrower Information */}
      <h3 style={{ color: "#1976d2" }}>
        Borrower Information
      </h3>

      <table
        style={{
          width: "100%",
          borderCollapse: "collapse",
          marginBottom: "20px",
        }}
      >
        <tbody>
          <tr>
            <td style={{ width: "45%", padding: "8px", fontWeight: "bold" }}>
              User ID
            </td>
            <td style={{ padding: "8px" }}>{userId}</td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Total Debt
            </td>
            <td style={{ padding: "8px" }}>₹{data?.total_debt}</td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Monthly Income
            </td>
            <td style={{ padding: "8px" }}>₹{data?.income}</td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Monthly EMI
            </td>
            <td style={{ padding: "8px" }}>₹{data?.emi}</td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Overdue Months
            </td>
            <td style={{ padding: "8px" }}>{data?.overdue_months}</td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Remaining EMI Months
            </td>
            <td style={{ padding: "8px" }}>
              {data?.remaining_emi_months}
            </td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Financial Score
            </td>
            <td style={{ padding: "8px" }}>
              {data?.score}/100
            </td>
          </tr>

          <tr>
            <td style={{ padding: "8px", fontWeight: "bold" }}>
              Risk Status
            </td>
            <td style={{ padding: "8px" }}>
              {data?.status}
            </td>
          </tr>
        </tbody>
      </table>

      <hr />

      {/* AI Recommendation */}
      <h3 style={{ color: "#1976d2" }}>
        AI Settlement Recommendation
      </h3>

      <div
        style={{
          background: "#f8f9fa",
          padding: "15px",
          borderRadius: "6px",
          lineHeight: "1.8",
          whiteSpace: "pre-wrap",
          marginBottom: "20px",
        }}
      >
       {aiAdvice
  ? aiAdvice.split("\n").map((line, index) => (
      <p key={index} style={{ margin: "6px 0" }}>
        • {line}
      </p>
    ))
  : "No recommendation generated."}
      </div>

      <hr />

      {/* Negotiation Letter */}
      <h3 style={{ color: "#1976d2" }}>
        AI Negotiation Letter
      </h3>

      <div
        style={{
          background: "#f8f9fa",
          padding: "15px",
          borderRadius: "6px",
          lineHeight: "1.8",
          whiteSpace: "pre-wrap",
          minHeight: "130px",
        }}
      >
        {negotiationLetter || "No negotiation letter generated."}
      </div>

      <hr style={{ marginTop: "30px" }} />

      <div
        style={{
          textAlign: "center",
          color: "#666",
          marginTop: "20px",
        }}
      >
        <strong>Generated by FinRelief AI</strong>

        <p>{new Date().toLocaleString()}</p>
      </div>
    </div>
  );
}

export default ReportPDF;